import { defineConfig } from 'rolldown'

export default defineConfig({
  input: {
    index: './src/index.ts',
    client: './src/client.ts',
    server: './src/server.ts',
    'lib/client/websocket-tracker': './src/client/websocket-tracker.ts',
    'bin/cmd': './src/bin/cmd.ts',
  },
  output: {
    dir: './dist',
    format: 'esm',
    sourcemap: true,
  },
  external: [
    '@thaunknown/simple-peer',
    '@thaunknown/simple-peer/lite.js',
    '@thaunknown/simple-websocket',
    'bencode',
    'bittorrent-peerid',
    'compact2string',
    'cross-fetch-ponyfill',
    'debug',
    'dgram',
    'http',
    'ip',
    'lru',
    'minimist',
    'once',
    'queue-microtask',
    'random-iterate',
    'run-parallel',
    'run-series',
    'socks',
    'string2compact',
    'uint8-util',
    'unordered-array-remove',
    'ws',
    'bufferutil',
    'utf-8-validate',
    'events',
    'querystring',
    'crypto',
  ],
  platform: 'node',
})
